---
- name: Configure time pi.
  hosts: all
  become: true

  vars_files: ['config.yml']

  handlers:
    - name: Include various service handlers.
      ansible.builtin.include_tasks: handlers/main.yml

  tasks:
    - name: Configure Raspberry Pi settings.
      ansible.builtin.include_tasks: tasks/pi-config.yml

    - name: Configure i226 Ethernet interface.
      ansible.builtin.include_tasks: tasks/i226.yml
      when: i226_force_1gbps

    - name: Configure GPS.
      ansible.builtin.include_tasks: tasks/gps.yml

    - name: Configure chrony.
      ansible.builtin.include_tasks: tasks/chrony.yml

    - name: Configure PTP.
      ansible.builtin.include_tasks: tasks/ptp.yml
