---
- name: Configure time pi.
  hosts: all
  become: true

  vars_files: ['config.yml']

  handlers:
    - name: restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted

    - name: restart gpsd
      ansible.builtin.service:
        name: gpsd
        state: restarted

  tasks:
    - ansible.builtin.include_tasks: tasks/pi-config.yml
    - ansible.builtin.include_tasks: tasks/gps.yml
    - ansible.builtin.include_tasks: tasks/chrony.yml
    - ansible.builtin.include_tasks: tasks/ptp.yml