---
- name: Configure time pi.
  hosts: all
  become: true

  vars_files: ['config.yml']

  handlers:
    - name: Restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted

    - name: Restart gpsd
      ansible.builtin.service:
        name: gpsd
        state: restarted

    - name: Restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

  tasks:
    - name: Configure Raspberry Pi settings.
      ansible.builtin.include_tasks: tasks/pi-config.yml

    - name: Configure i226 Ethernet interface.
      ansible.builtin.include_tasks: tasks/i226.yml
      when: i226_force_1gbps

    - name: Configure GPS.
      ansible.builtin.include_tasks: tasks/gps.yml

    - name: Configure chrony.
      ansible.builtin.include_tasks: tasks/chrony.yml

    - name: Configure PTP.
      ansible.builtin.include_tasks: tasks/ptp.yml
