---
- name: Configure client nodes.
  hosts: clients
  become: true

  vars_files: ['config.yml']

  tasks:
    - name: Install linuxptp.
      ansible.builtin.apt:
        name: linuxptp
        state: present
