---
- name: Install GPS prerequisites.
  ansible.builtin.apt:
    name:
      - gpsd
      - gpsd-clients
    state: present

- name: Configure gpsd.
  ansible.builtin.lineinfile:
    dest: /etc/default/gpsd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  notify: Restart gpsd
  with_items:
    - regexp: '^DEVICES='
      line: 'DEVICES="{{ gpsd_devices }}"'
    - regexp: '^GPSD_OPTIONS='
      line: 'GPSD_OPTIONS="{{ gpsd_options }}"'

- name: Ensure gpsd is running.
  ansible.builtin.service:
    name: gpsd
    state: started
    enabled: true

# TODO: sudo ln -s /dev/ttyAMA0 /dev/ttyS10
- name: TODO - Add script to symlink /dev/ttyAMA0 to /dev/ttyS10 at boot
  ansible.builtin.meta: noop
