---
- name: Install linuxptp.
  ansible.builtin.apt:
    name: linuxptp
    state: present

# TODO: Set up NIC as grandmaster, configure phc2sys, and set up testptp
# See: https://github.com/geerlingguy/time-pi/issues/1
# sudo ptp4l -i eth1 -m
